

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log
      directory: logs


spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
     #thymeleaf end
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test
    driverClassName: com.mysql.jdbc.Driver
    #Druid
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小、最大、最小
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #filters: stat
    #maxActive: 20
    #initialSize: 1
    #连接超时
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: top.catfish.test2_shiro.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
debug: true
